version: '3'
services:
  web:
    build: app
    restart: always
    image: comses/skopeui/dev:latest
    depends_on:
      - mongo
    volumes:
      - ./app:/code
      - /code/node_modules
    env_file:
      - secrets/oauth.env
  mongo:
    image: mongo:4
    restart: always
    env_file:
      - secrets/mongo.env
    volumes:
      - ./docker/shared/mongo:/data/db
  django:
    build: django
    depends_on:
      - db
    volumes:
      - ./secrets:/run/secrets
  db:
    image: comses/postgis:10
    volumes:
      - ./docker/shared/pgdata:/var/lib/postgresql/data
      - ./secrets:/run/secrets
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-passwd"
      POSTGRES_DB: "skope"
