version: '3.8'
services:
  web:
    build: app
    restart: always
    image: comses/skopeui/dev:latest
    volumes:
      - ./app:/code
      - /code/node_modules
    env_file:
      - secrets/oauth.env
