version: '3'
services:
  django:
    build:
      args:
        RUN_SCRIPT: "./docker/run/dev.sh"
    image: comses/skopebackend/dev:latest
    environment:
      DJANGO_SETTINGS_MODULE: "skope.settings.dev"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./django:/code
